### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by itsmealwin** [stoeffel/material-iterm#4]
Hi,

thank you for the lovely Iterm-theme. This in itself is not an issue-report, just a personal interest question. I have been searching and wondering about the font you are using in the screen shot. Would you please be so kind and let me know?

Thank you in advance,
Alwin

**Comment by itsmealwin** [comment]
Sorry, I should have searched a little bit more dilligently. I poked around your repos and found your dotfiles that contain the font I was looking for. It was Inconsolata-Awesome.

**Comment by stoeffel** [comment]
Hi. Thanks a lot! Glad you like it. Hmmm... I don't know what font I had when I took the screenshot. I changed it so many times since. My best guess is [inconsolata](https://www.google.com/fonts/specimen/Inconsolata). Currently I'm using Fira code. I'm hoping that iterm2 will soon support ligatures :sunglasses: 

Cheers stöffel

**Comment by stoeffel** [comment]
haha. commented at the same time.
